<program>    ::= { <statement> }

<statement>  ::= <keyword> <identifier> <assignment> <expression> ";"
               | <identifier> <assignment> <expression> ";"

<expression> ::= <term> { <operator> <term> }

<term>       ::= <number>
               | <identifier>

<number>     ::= <digit> { <digit> }
<digit>      ::= "0" | "1" | ... | "9"
<identifier> ::= <letter> { <letter> | <digit> }
<letter>     ::= "a" | ... | "z" | "A" | ... | "Z"

<operator>   ::= "+" | "-" | "*" | "/"
<assignment> ::= "="
<keyword>    ::= "let" | "var"

